// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8T_37FK1coLyrxDijr14fps7E_zQu3sQ',
    appId: '1:829773422873:web:59d8580009c9c6b42aa588',
    messagingSenderId: '829773422873',
    projectId: 'hello-chat-bc1fb',
    authDomain: 'hello-chat-bc1fb.firebaseapp.com',
    storageBucket: 'hello-chat-bc1fb.firebasestorage.app',
    measurementId: 'G-B4F96RLN31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzFh0qwXMQnhNB5aCb-87XMn02ynKkrto',
    appId: '1:829773422873:android:3b6da0d6053756ca2aa588',
    messagingSenderId: '829773422873',
    projectId: 'hello-chat-bc1fb',
    storageBucket: 'hello-chat-bc1fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHsB3vd5BfdjaVp0cF6hJj5klesKro96Q',
    appId: '1:829773422873:ios:3b696d312027ab3d2aa588',
    messagingSenderId: '829773422873',
    projectId: 'hello-chat-bc1fb',
    storageBucket: 'hello-chat-bc1fb.firebasestorage.app',
    iosBundleId: 'com.buxhiitech.helloChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHsB3vd5BfdjaVp0cF6hJj5klesKro96Q',
    appId: '1:829773422873:ios:3b696d312027ab3d2aa588',
    messagingSenderId: '829773422873',
    projectId: 'hello-chat-bc1fb',
    storageBucket: 'hello-chat-bc1fb.firebasestorage.app',
    iosBundleId: 'com.buxhiitech.helloChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8T_37FK1coLyrxDijr14fps7E_zQu3sQ',
    appId: '1:829773422873:web:e3b2fe920283053a2aa588',
    messagingSenderId: '829773422873',
    projectId: 'hello-chat-bc1fb',
    authDomain: 'hello-chat-bc1fb.firebaseapp.com',
    storageBucket: 'hello-chat-bc1fb.firebasestorage.app',
    measurementId: 'G-S1GVN8CG12',
  );
}
